### ISSUE TITLE
NPM: component emitter depencency does not work 

### ISSUE THREAD

**Issue by marcopeg** [component/bus#4]
> This report is relevant to _NPM_ package system only

This module define a `package.json` dependency named `emitter-component` which does not exists because you component/emitter package is registered as `component-emitter`.

Then the `index.js` entry point requires the generic `emitter` package which does not exists at all.

**Comment by dominicbarnes** [comment]
Yeah, I just ran into this myself. This module only seems to work when build via browserify for client-side use. I'll see if I can fix for node itself.
